format = "$ssh$directory$git_branch$line_break$character"
[directory]
format = "(bg:#212223 fg#212223)[](bg:transparent fg:#212223)[󰣇 ](bg:#212223 fg:#d0d0d0)[](bg:#212223 fg:#d0d0d0)[ ](bg:#d0d0d0 fg:#212223)[(bg:#d0d0d0 fg:#212223)$path](bg:#d0d0d0 fg:#212223)[](bg:transparent fg:#d0d0d0)"
style = "bg:#000000 fg:#454acc"
[git_branch]
format = "[ ](bg:transparent fg:transparent)[on ](bg:transparent fg:default)[ $branch](bg:transparent fg:purple)"
[character]
format = "[❯ ](bg:transparent fg:#d0d0d0)"
[custom.ssh]
command = '[[ -n "$SSH_CONNECTION" ]] && echo " SSH "'
when = '[[ -n "$SSH_CONNECTION" ]]'
format = '[$output]'
